---
env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'airbnb'
parser: 'babel-eslint'
plugins:
  - react
rules:
  import/extensions: 0
  no-console: 0
  no-underscore-dangle: 0
  react/prop-types: 0
